### ISSUE TITLE
Check if C2 container already exist

### ISSUE THREAD

**Issue by 0xblank** [ip2root/ip2root#64]

**Comment by 0xblank** [comment]
Error example:

```shell
[+] Deploying C2 container
Traceback (most recent call last):
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/create?name=empire

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blank/ip2root/main.py", line 155, in <module>
    main()
  File "/home/blank/ip2root/main.py", line 113, in main
    c2_infos = c2.c2()
  File "/home/blank/ip2root/c2.py", line 27, in c2
    infos = deploy_c2() 
  File "/home/blank/ip2root/c2.py", line 44, in deploy_c2
    container = client.containers.run(image='bcsecurity/empire:latest', ports={'1337/tcp':1337, '5000/tcp':5000, '{}/tcp'.format(C2_LISTENER_PORT):C2_LISTENER_PORT}, name='empire', tty=True, detach=True)
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/models/containers.py", line 847, in run
    container = self.create(image=image, command=command,
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/models/containers.py", line 906, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/blank/ip2root/venv_ip2root/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=empire: Conflict ("Conflict. The container name "/empire" is already in use by container "6bdec161675fc1c2a722d6cbc55d4343ed2aede9e0740cee4ac4cb2a7f4f58de". You have to remove (or rename) that container to be able to reuse that name.")
```

**Comment by Steels03** [comment]
Which commit on which branch are you using ? Works with last commit on branch dev-c2 @0xblank

**Comment by 0xblank** [comment]
last commit on branch `dev` 2908065fa9ced6b8ae6aa4e65b21d4de29f4ddb3
